# Generated by Django 4.2.16 on 2026-09-18 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Hospital Name')),
                ('type', models.CharField(choices=[('district', 'District Hospital'), ('private', 'Private Hospital'), ('community', 'Community Hospital'), ('teaching', 'Teaching Hospital'), ('clinic', 'Clinic/Health Post')], default='district', max_length=20, verbose_name='Hospital Type')),
                ('address', models.TextField(verbose_name='Address')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('municipality', models.CharField(blank=True, default='', max_length=100, verbose_name='Municipality')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, default='', verbose_name='Website')),
                ('emergency_contact', models.CharField(blank=True, default='', max_length=30, verbose_name='Emergency Contact')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Verification Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Service Name')),
                ('category', models.CharField(choices=[('icu', 'Intensive Care Unit (ICU)'), ('nicu', 'Neonatal ICU (NICU)'), ('ct', 'CT Scan'), ('mri', 'MRI'), ('dialysis', 'Dialysis'), ('cardiology', 'Cardiology'), ('maternity', 'Maternity / Obstetrics'), ('bloodbank', 'Blood Bank'), ('surgery', 'Emergency Surgery'), ('emergency', 'Emergency Department'), ('orthopedics', 'Orthopedics'), ('neurology', 'Neurology'), ('pediatrics', 'Pediatrics'), ('ophthalmology', 'Ophthalmology'), ('ent', 'ENT'), ('other', 'Other')], default='other', max_length=20, verbose_name='Category')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_type', models.CharField(choices=[('bed', 'General Bed'), ('icu', 'ICU Bed'), ('nicu', 'NICU Bed'), ('specialist', 'Specialist'), ('test', 'Diagnostic Test'), ('equipment', 'Equipment'), ('blood', 'Blood'), ('emergency', 'Emergency')], max_length=20, verbose_name='Availability Type')),
                ('status', models.CharField(choices=[('available', 'Available'), ('limited', 'Limited'), ('unavailable', 'Unavailable'), ('full', 'Full'), ('unknown', 'Unknown')], default='unknown', max_length=20, verbose_name='Status')),
                ('available_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Available Count')),
                ('total_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Count')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('api', 'API/Integration'), ('auto', 'Automated')], default='manual', max_length=10, verbose_name='Data Source')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_records', to='hospitals.hospital', verbose_name='Hospital')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availability_records', to='hospitals.service', verbose_name='Service')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availability_updates', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Availability',
                'verbose_name_plural': 'Availability Records',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HospitalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_services', to='hospitals.hospital', verbose_name='Hospital')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_services', to='hospitals.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Hospital Service',
                'verbose_name_plural': 'Hospital Services',
                'ordering': ['hospital', 'service'],
                'unique_together': {('hospital', 'service')},
            },
        ),
    ]
