# Generated by Django 4.2.16 on 2026-09-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.CheckConstraint(check=models.Q(('available_count__isnull', True), ('total_count__isnull', True), ('available_count__lte', models.F('total_count')), _connector='OR'), name='availability_count_lte_total'),
        ),
    ]
