# Generated by Django 6.1.1 on 2026-09-19 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_validate_availability_counts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Doctor Name')),
                ('specialty', models.CharField(max_length=200, verbose_name='Specialty')),
                ('qualification', models.CharField(blank=True, default='', max_length=300, verbose_name='Qualification')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Contact Phone')),
                ('duty_status', models.CharField(choices=[('on_duty', 'On Duty'), ('off_duty', 'Off Duty'), ('on_leave', 'On Leave'), ('unknown', 'Unknown')], default='unknown', max_length=20, verbose_name='Duty Status')),
                ('consultation_days', models.CharField(blank=True, default='', help_text='E.g. "Mon, Wed, Fri" or "Mon–Fri"', max_length=200, verbose_name='Consultation Days')),
                ('consultation_time', models.CharField(blank=True, default='', help_text='E.g. "9:00 AM – 1:00 PM"', max_length=100, verbose_name='Consultation Time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='hospitals.hospital', verbose_name='Hospital')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_updates', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['hospital', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PatientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.CharField(editable=False, max_length=12, unique=True, verbose_name='Request Code')),
                ('service_name_freetext', models.CharField(blank=True, default='', max_length=300, verbose_name='Service (free text)')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Contact Phone')),
                ('patient_age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Patient Age')),
                ('condition_summary', models.CharField(max_length=500, verbose_name='Condition Summary')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Additional Notes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('call_required', 'Call Required'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('response_note', models.TextField(blank=True, default='', verbose_name='Hospital Response Note')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Responded At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('destination_hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_requests', to='hospitals.hospital', verbose_name='Destination Hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_requests', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_patient_requests', to=settings.AUTH_USER_MODEL, verbose_name='Responded By')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_requests', to='hospitals.service', verbose_name='Requested Service')),
            ],
            options={
                'verbose_name': 'Patient Request',
                'verbose_name_plural': 'Patient Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientRequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, default='', max_length=20, verbose_name='Old Status')),
                ('new_status', models.CharField(max_length=20, verbose_name='New Status')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_request_events', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hospitals.patientrequest', verbose_name='Patient Request')),
            ],
            options={
                'verbose_name': 'Patient Request Event',
                'verbose_name_plural': 'Patient Request Events',
                'ordering': ['created_at'],
            },
        ),
    ]
