# Generated by Django 4.2.16 on 2026-09-18 09:17

import apps.referrals.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(default=apps.referrals.models.generate_referral_code, editable=False, max_length=10, unique=True, verbose_name='Referral Code')),
                ('urgency', models.CharField(choices=[('emergency', 'Emergency'), ('urgent', 'Urgent'), ('routine', 'Routine')], default='routine', max_length=10, verbose_name='Urgency')),
                ('patient_age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Patient Age')),
                ('patient_gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('other', 'Other')], default='', max_length=5, verbose_name='Patient Gender')),
                ('patient_condition_summary', models.CharField(max_length=500, verbose_name='Patient Condition Summary')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Reason for Referral')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('call_required', 'Call Required'), ('patient_sent', 'Patient Sent'), ('patient_arrived', 'Patient Arrived'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Responded At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_referrals', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('destination_facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_referrals', to='hospitals.hospital', verbose_name='Destination Facility')),
                ('referring_facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_referrals', to='hospitals.hospital', verbose_name='Referring Facility')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_referrals', to=settings.AUTH_USER_MODEL, verbose_name='Responded By')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='hospitals.service', verbose_name='Service Requested')),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, default='', max_length=20, verbose_name='Old Status')),
                ('new_status', models.CharField(max_length=20, verbose_name='New Status')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_events', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='referrals.referral', verbose_name='Referral')),
            ],
            options={
                'verbose_name': 'Referral Event',
                'verbose_name_plural': 'Referral Events',
                'ordering': ['created_at'],
            },
        ),
    ]
