# Generated by Django 4.2.16 on 2026-09-18 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('create', 'Record Created'), ('update', 'Record Updated'), ('delete', 'Record Deleted'), ('status_change', 'Status Changed'), ('referral_create', 'Referral Created'), ('referral_response', 'Referral Response'), ('referral_status_update', 'Referral Status Updated'), ('availability_update', 'Availability Updated'), ('hospital_create', 'Hospital Created'), ('hospital_update', 'Hospital Updated'), ('user_create', 'User Created'), ('user_update', 'User Updated'), ('password_change', 'Password Changed'), ('register', 'User Registered'), ('other', 'Other')], max_length=30, verbose_name='Action')),
                ('entity_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Entity Type')),
                ('entity_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Entity ID')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'permissions': [('view_audit_logs', 'Can view audit logs')],
            },
        ),
    ]
